name: nix-setup

runs:
  using: "composite"

  steps:
    - name: Install Determinate nix
      id: nix-install
      uses: DeterminateSystems/determinate-nix-action@1361e7900eb437fb341f0f226e8fbd9a0d8284fa # v3.17.2

    - name: Setup nix cache
      id: nix-cache
      uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
