name: nix-setup

runs:
  using: "composite"

  steps:
    - name: Install Determinate nix
      id: nix-install
      uses: DeterminateSystems/determinate-nix-action@32cb6a5ae30bb0dfc996fa7baf8bf1ed28442fa4 # v3.17.3

    - name: Setup nix cache
      id: nix-cache
      uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
