name: nix-setup

runs:
  using: "composite"

  steps:
    - name: Install Determinate nix
      id: nix-install
      uses: DeterminateSystems/determinate-nix-action@131015bad844610e5e6300f8a143bf625d3e74f4 # v3.17.0

    - name: Setup nix cache
      id: nix-cache
      uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
