---
# cSpell:words hyprland nixpkgs
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
caseSensitive: false
ignorePaths:
  - result
  - '**/secrets.yaml'
dictionaryDefinitions:
  - name: project
    path: ./.cspell.txt
    addWords: true
  - name: hyprland
    path: https://gist.githubusercontent.com/Joker9944/855a8af8d140408a9353a300e581f9b2/raw/hyprland.txt
    addWords: false
  - name: linux
    path: https://gist.githubusercontent.com/Joker9944/855a8af8d140408a9353a300e581f9b2/raw/linux.txt
    addWords: false
  - name: nix
    path: https://gist.githubusercontent.com/Joker9944/855a8af8d140408a9353a300e581f9b2/raw/nix.txt
    addWords: false
  - name: nixpkgs
    path: https://gist.githubusercontent.com/Joker9944/855a8af8d140408a9353a300e581f9b2/raw/nixpkgs.txt
    addWords: false
  - name: shell
    path: https://gist.githubusercontent.com/Joker9944/855a8af8d140408a9353a300e581f9b2/raw/shell.txt
    addWords: false
  - name: user
    path: https://gist.githubusercontent.com/Joker9944/855a8af8d140408a9353a300e581f9b2/raw/user.txt
    addWords: false
dictionaries:
  - project
  - user
languageSettings:
  - languageId: conf
    locale: 'en'
    dictionaries:
      - hyprland
  - languageId: nix
    locale: 'en'
    dictionaries:
      - hyprland
      - linux
      - nix
      - nixpkgs
      - shell
  - languageId: sh
    locale: 'en'
    dictionaries:
      - linux
      - shell
