# https://code.visualstudio.com/api/references/theme-color
{
  flake,
  variant,
  displayName,
}:
{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.schemes.${variant};
  libSchemes = flake.lib.libSchemes;

  jsonFormat = pkgs.formats.json { };
in
{
  options.schemes.${variant} =
    let
      inherit (lib)
        literalExpression
        mkEnableOption
        mkOption
        types
        ;
      customTypes = libSchemes.types;
    in
    {
      enable = mkEnableOption "${displayName} theming based on a scheme";

      scheme = mkOption {
        type = customTypes.scheme;
        default = config.schemes.scheme;
        description = ''
          Color scheme used to customize ${displayName}.
        '';
      };

      profiles = mkOption {
        type = types.listOf types.str;
        default = [ "default" ];
        example = literalExpression ''[ "default" "nix" ]'';
        description = ''
          Profiles the theme is installed into. A name no profile carries creates one.
        '';
      };

      colors = mkOption {
        type = types.attrsOf types.str;
        default = { };
        example = literalExpression ''{ "editor.background" = "#1E1823"; }'';
        description = ''
          Workbench colors merged over the generated ones. The output is a derivation,
          so this is the override channel — there are no per-slot options.
        '';
      };

      tokenColors = mkOption {
        type = types.listOf jsonFormat.type;
        default = [ ];
        description = ''
          TextMate rules appended after the generated ones, where a later rule outranks
          an earlier one on equal scope specificity.
        '';
      };

      package = mkOption {
        type = types.package;
        readOnly = true;
        description = ''
          The generated theme extension. Reach for it to theme an editor that has no
          module of its own.
        '';
      };
    };

  config =
    let
      inherit (cfg.scheme.meta) name slug;

      publisher = "nix-schemes";
      extensionId = "${publisher}.${slug}";
      themeFileName = "${slug}-color-theme.json";

      theme = import ./theme cfg.scheme;

      themeFile = jsonFormat.generate themeFileName (
        theme
        // {
          colors = theme.colors // cfg.colors;
          tokenColors = theme.tokenColors ++ cfg.tokenColors;
        }
      );

      manifestFile = jsonFormat.generate "package.json" {
        inherit publisher;
        name = slug;
        displayName = name;
        description = "${name} generated by nix-schemes.";
        version = "1.0.0";
        engines.vscode = "^1.70.0";
        categories = [ "Themes" ];
        contributes.themes = [
          {
            label = name;
            uiTheme = if cfg.scheme.meta.variant == "light" then "vs" else "vs-dark";
            path = "./themes/${themeFileName}";
          }
        ];
      };

      # home-manager reads the `vscodeExt*` attrs to build `extensions.json`, and falls
      # back to reading the store path when `vscodeExtUniqueId` is absent — which is IFD.
      themePackage =
        pkgs.runCommandLocal "vscode-${slug}-theme"
          {
            passthru = {
              version = "1.0.0";
              vscodeExtPublisher = publisher;
              vscodeExtName = slug;
              vscodeExtUniqueId = extensionId;
            };
          }
          ''
            dst="$out/share/vscode/extensions/${extensionId}"
            mkdir -p "$dst/themes"
            install --mode=644 ${manifestFile} "$dst/package.json"
            install --mode=644 ${themeFile} "$dst/themes/${themeFileName}"
          '';
    in
    lib.mkIf cfg.enable {
      schemes.${variant}.package = themePackage;

      programs.${variant}.profiles = lib.genAttrs cfg.profiles (_: {
        extensions = [ themePackage ];
        userSettings."workbench.colorTheme" = lib.mkDefault name;
      });
    };
}
