name: nix-flake-update

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:

  nix-flake-update:

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:

      - name: Repository Checkout
        id: git-checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup nix
        id: nix-setup
        uses: Joker9944/nix-config/.github/composites/nix-setup@main

      - name: Git Identity
        id: git-identity
        uses: ./.github/composites/git-identity

      - name: Update Flakes
        id: nix-update
        shell: bash

        run: |
          mapfile -t flake_dirs < <(find . -name "flake.nix" -exec dirname {} + | sort -u)

          for flake_dir in "${flake_dirs[@]}"; do
            echo "Updating flake in: $flake_dir"
            nix flake update --flake "$flake_dir" --commit-lock-file --option commit-lock-file-summary "flake: update $flake_dir/flake.lock"
          done

      - name: Create Pull Request
        id: update-pr
        uses: ./.github/composites/update-pr

        with:
          branch: ci/nix-flake-update
          title: "chore(deps): lock file maintenance"
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
