name: nix-flake-build

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  nix-flake-build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - attr: .#homeConfigurations."joker9944@HAL9000".activationPackage
          - attr: .#homeConfigurations."joker9944@wintermute".activationPackage
          - attr: .#nixosConfigurations.HAL9000.config.system.build.toplevel # cSpell:words toplevel
          - attr: .#nixosConfigurations.wintermute.config.system.build.toplevel

    steps:
      - name: Repository checkout
        id: git-checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        with:
          submodules: true

      - name: Setup nix
        id: nix-setup
        uses: Joker9944/nix-config/.github/composites/nix-setup@main
        with:
          # cSpell:disable
          extra-conf: |
            extra-substituters = https://nix-community.cachix.org https://hyprland.cachix.org https://cache.nixos-cuda.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M
          # cSpell:enable

      - name: Build derivations
        id: nix-build

        run: |
          nix build --print-build-logs ${{ matrix.attr }} --no-link
